import {Player} from 'clashofclans.js';
import {PlayerSnapshot} from './types.player';
import {PlayerTag, TownHallLevel} from './types';
import {
    HOME_EQUIPMENT_ID_ARCHER_PUPPET,
    HOME_EQUIPMENT_ID_BARBARIAN_PUPPET,
    HOME_EQUIPMENT_ID_EARTHQUAKE_BOOTS,
    HOME_EQUIPMENT_ID_ETERNAL_TOME,
    HOME_EQUIPMENT_ID_FIREBALL,
    HOME_EQUIPMENT_ID_FROZEN_ARROW,
    HOME_EQUIPMENT_ID_GIANT_ARROW,
    HOME_EQUIPMENT_ID_GIANT_GAUNTLET,
    HOME_EQUIPMENT_ID_HASTE_VIAL,
    HOME_EQUIPMENT_ID_HEALER_PUPPET,
    HOME_EQUIPMENT_ID_HEALING_TOME,
    HOME_EQUIPMENT_ID_HOG_RIDER_PUPPET,
    HOME_EQUIPMENT_ID_INVISIBILITY_VIAL,
    HOME_EQUIPMENT_ID_LIFE_GEM,
    HOME_EQUIPMENT_ID_MAGIC_MIRROR,
    HOME_EQUIPMENT_ID_RAGE_GEM,
    HOME_EQUIPMENT_ID_RAGE_VIAL,
    HOME_EQUIPMENT_ID_ROCKET_SPEAR,
    HOME_EQUIPMENT_ID_ROYAL_GEM,
    HOME_EQUIPMENT_ID_SEEKING_SHIELD,
    HOME_EQUIPMENT_ID_SPIKY_BALL,
    HOME_EQUIPMENT_ID_VAMPSTACHE,
    HOME_HERO_ID_ARCHER_QUEEN,
    HOME_HERO_ID_BARBARIAN_KING,
    HOME_HERO_ID_GRAND_WARDEN,
    HOME_HERO_ID_ROYAL_CHAMPION, HOME_TROOP_ID_ANGRY_JELLY, HOME_TROOP_ID_ARCHER, HOME_TROOP_ID_BARBARIAN,
    HOME_TROOP_ID_BATTLE_BLIMP,
    HOME_TROOP_ID_BATTLE_DRILL, HOME_TROOP_ID_DIGGY, HOME_TROOP_ID_ELECTRO_OWL,
    HOME_TROOP_ID_FLAME_FLINGER, HOME_TROOP_ID_FROSTY, HOME_TROOP_ID_GIANT,
    HOME_TROOP_ID_LASSI,
    HOME_TROOP_ID_LOG_LAUNCHER, HOME_TROOP_ID_MIGHTY_YAK, HOME_TROOP_ID_PHOENIX, HOME_TROOP_ID_POISON_LIZARD,
    HOME_TROOP_ID_SIEGE_BARRACKS, HOME_TROOP_ID_SPIRIT_FOX,
    HOME_TROOP_ID_STONE_SLAMMER, HOME_TROOP_ID_UNICORN,
    HOME_TROOP_ID_WALL_WRECKER,
} from './constants-offense-ids';
import {toObjKeyedBy} from '../pure';

export const toPlayerSnapshot = (player: Player): PlayerSnapshot => {
    const heroes = player.heroes.reduce(toObjKeyedBy('id'));
    const equipment = player.heroEquipment.reduce(toObjKeyedBy('id'));
    const pets = player.heroPets.reduce(toObjKeyedBy('id'));
    const troops = player.troops.reduce(toObjKeyedBy('id'));
    const spells = player.spells.reduce(toObjKeyedBy('id'));
    const siege = player.siegeMachines.reduce(toObjKeyedBy('id'));

    return {
        id  : player.tag,
        name: player.name,

        th       : player.townHallLevel,
        th_weapon: player.townHallWeaponLevel,

        h_bk: heroes[HOME_HERO_ID_BARBARIAN_KING],
        h_aq: heroes[HOME_HERO_ID_ARCHER_QUEEN],
        h_gw: heroes[HOME_HERO_ID_GRAND_WARDEN],
        h_rc: heroes[HOME_HERO_ID_ROYAL_CHAMPION],

        e_gg : equipment[HOME_EQUIPMENT_ID_GIANT_GAUNTLET],
        e_sb : equipment[HOME_EQUIPMENT_ID_SPIKY_BALL],
        e_eqb: equipment[HOME_EQUIPMENT_ID_EARTHQUAKE_BOOTS],
        e_vs : equipment[HOME_EQUIPMENT_ID_VAMPSTACHE],
        e_bpu: equipment[HOME_EQUIPMENT_ID_BARBARIAN_PUPPET],
        e_rv : equipment[HOME_EQUIPMENT_ID_RAGE_VIAL],
        e_ga : equipment[HOME_EQUIPMENT_ID_GIANT_ARROW],
        e_hpu: equipment[HOME_EQUIPMENT_ID_HEALER_PUPPET],
        e_iv : equipment[HOME_EQUIPMENT_ID_INVISIBILITY_VIAL],
        e_mm : equipment[HOME_EQUIPMENT_ID_MAGIC_MIRROR],
        e_fa : equipment[HOME_EQUIPMENT_ID_FROZEN_ARROW],
        e_apu: equipment[HOME_EQUIPMENT_ID_ARCHER_PUPPET],
        e_fb : equipment[HOME_EQUIPMENT_ID_FIREBALL],
        e_et : equipment[HOME_EQUIPMENT_ID_ETERNAL_TOME],
        e_ht : equipment[HOME_EQUIPMENT_ID_HEALING_TOME],
        e_lg : equipment[HOME_EQUIPMENT_ID_LIFE_GEM],
        e_rg : equipment[HOME_EQUIPMENT_ID_RAGE_GEM],
        e_ss : equipment[HOME_EQUIPMENT_ID_SEEKING_SHIELD],
        e_hv : equipment[HOME_EQUIPMENT_ID_HASTE_VIAL],
        e_hog: equipment[HOME_EQUIPMENT_ID_HOG_RIDER_PUPPET],
        e_rs : equipment[HOME_EQUIPMENT_ID_ROCKET_SPEAR],
        e_roy: equipment[HOME_EQUIPMENT_ID_ROYAL_GEM],

        p_la: pets[HOME_TROOP_ID_LASSI],
        p_eo: pets[HOME_TROOP_ID_ELECTRO_OWL],
        p_my: pets[HOME_TROOP_ID_MIGHTY_YAK],
        p_u : pets[HOME_TROOP_ID_UNICORN],
        p_f : pets[HOME_TROOP_ID_FROSTY],
        p_pl: pets[HOME_TROOP_ID_POISON_LIZARD],
        p_d : pets[HOME_TROOP_ID_DIGGY],
        p_p : pets[HOME_TROOP_ID_PHOENIX],
        p_sf: pets[HOME_TROOP_ID_SPIRIT_FOX],
        p_aj: pets[HOME_TROOP_ID_ANGRY_JELLY],

        t_barb  : troops[HOME_TROOP_ID_BARBARIAN],
        t_arch  : troops[HOME_TROOP_ID_ARCHER],
        t_giant : troops[HOME_TROOP_ID_GIANT],
        t_gob   : troops[HOME_TROOP_ID],
        t_wb    : troops[HOME_TROOP_ID],
        t_loon  : troops[HOME_TROOP_ID],
        t_wiz   : troops[HOME_TROOP_ID],
        t_heal  : troops[HOME_TROOP_ID],
        t_drag  : troops[HOME_TROOP_ID],
        t_pekka : troops[HOME_TROOP_ID],
        t_bdrag : troops[HOME_TROOP_ID],
        t_miner : troops[HOME_TROOP_ID],
        t_edrag : troops[HOME_TROOP_ID],
        t_yeti  : troops[HOME_TROOP_ID],
        t_drider: troops[HOME_TROOP_ID],
        t_etitan: troops[HOME_TROOP_ID],
        t_rrider: troops[HOME_TROOP_ID],
        t_minion: troops[HOME_TROOP_ID],
        t_hrider: troops[HOME_TROOP_ID],
        t_valk  : troops[HOME_TROOP_ID],
        t_golem : troops[HOME_TROOP_ID],
        t_witch : troops[HOME_TROOP_ID],
        t_hound : troops[HOME_TROOP_ID],
        t_bowler: troops[HOME_TROOP_ID],
        t_ig    : troops[HOME_TROOP_ID],
        t_hh    : troops[HOME_TROOP_ID],
        t_aw    : troops[HOME_TROOP_ID],
        t_druid : troops[HOME_TROOP_ID],

        sp_zap   : spells[HOME_SPELL_ID],
        sp_heal  : spells[HOME_SPELL_ID],
        sp_rage  : spells[HOME_SPELL_ID],
        sp_jump  : spells[HOME_SPELL_ID],
        sp_freeze: spells[HOME_SPELL_ID],
        sp_clone : spells[HOME_SPELL_ID],
        sp_invis : spells[HOME_SPELL_ID],
        sp_recall: spells[HOME_SPELL_ID],
        sp_poison: spells[HOME_SPELL_ID],
        sp_eq    : spells[HOME_SPELL_ID],
        sp_haste : spells[HOME_SPELL_ID],
        sp_skelly: spells[HOME_SPELL_ID],
        sp_bat   : spells[HOME_SPELL_ID],
        sp_og    : spells[HOME_SPELL_ID],

        si_ww: siege[HOME_TROOP_ID_WALL_WRECKER],
        si_bb: siege[HOME_TROOP_ID_BATTLE_BLIMP],
        si_ss: siege[HOME_TROOP_ID_STONE_SLAMMER],
        si_sb: siege[HOME_TROOP_ID_SIEGE_BARRACKS],
        si_ll: siege[HOME_TROOP_ID_LOG_LAUNCHER],
        si_ff: siege[HOME_TROOP_ID_FLAME_FLINGER],
        si_bd: siege[HOME_TROOP_ID_BATTLE_DRILL],
    };
};
