import {describe, it, expect} from 'vitest';
import {mapWars} from '#src/clashking/map-wars.ts';
import console from 'node:console';
import {show} from '../../util.ts';

const given = [{
    state               : 'warEnded',
    teamSize            : 25,
    attacksPerMember    : 2,
    battleModifier      : 'none',
    preparationStartTime: '20240824T031224.000Z',
    startTime           : '20240825T021224.000Z',
    endTime             : '20240826T021224.000Z',
    clan                : {
        tag      : '#U8YURJG0',
        name     : '212crew',
        badgeUrls: {
            small : 'https://api-assets.clashofclans.com/badges/70/EkOVwQ8D5PHoKi5sRlvLdvzoPOFgjB-JsPxFXzrIO4Q.png',
            large : 'https://api-assets.clashofclans.com/badges/512/EkOVwQ8D5PHoKi5sRlvLdvzoPOFgjB-JsPxFXzrIO4Q.png',
            medium: 'https://api-assets.clashofclans.com/badges/200/EkOVwQ8D5PHoKi5sRlvLdvzoPOFgjB-JsPxFXzrIO4Q.png',
        },
        clanLevel            : 16,
        attacks              : 38,
        stars                : 68,
        destructionPercentage: 95.12,
        members              : [{
            tag          : '#PP0JVP00',
            name         : 'Antonio',
            townhallLevel: 13,
            mapPosition  : 20,
            attacks      : [{
                attackerTag          : '#PP0JVP00',
                defenderTag          : '#8GCC0RPL8',
                stars                : 2,
                destructionPercentage: 76,
                order                : 18,
                duration             : 175,
            }, {
                attackerTag          : '#PP0JVP00',
                defenderTag          : '#QRGCQ9PRL',
                stars                : 2,
                destructionPercentage: 67,
                order                : 53,
                duration             : 139,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#8GCC0RPL8',
                defenderTag          : '#PP0JVP00',
                stars                : 3,
                destructionPercentage: 100,
                order                : 15,
                duration             : 151,
            },
        }, {
            tag          : '#8ULU8LUG0',
            name         : 'Portgas D. Ace',
            townhallLevel: 16,
            mapPosition  : 10,
            attacks      : [{
                attackerTag          : '#8ULU8LUG0',
                defenderTag          : '#20RYGQQU0',
                stars                : 2,
                destructionPercentage: 65,
                order                : 38,
                duration             : 169,
            }, {
                attackerTag          : '#8ULU8LUG0',
                defenderTag          : '#Q8VYCLJVL',
                stars                : 3,
                destructionPercentage: 100,
                order                : 54,
                duration             : 174,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#QJYRYGJG0',
                defenderTag          : '#8ULU8LUG0',
                stars                : 3,
                destructionPercentage: 100,
                order                : 26,
                duration             : 140,
            },
        }, {
            tag          : '#Q20LRR0YY',
            name         : 'Nancy',
            townhallLevel: 15,
            mapPosition  : 3,
            attacks      : [{
                attackerTag          : '#Q20LRR0YY',
                defenderTag          : '#88LJUYVVG',
                stars                : 3,
                destructionPercentage: 100,
                order                : 67,
                duration             : 160,
            }, {
                attackerTag          : '#Q20LRR0YY',
                defenderTag          : '#8GCC0RPL8',
                stars                : 3,
                destructionPercentage: 100,
                order                : 69,
                duration             : 85,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#2002GULCL',
                defenderTag          : '#Q20LRR0YY',
                stars                : 3,
                destructionPercentage: 100,
                order                : 75,
                duration             : 107,
            },
        }, {
            tag          : '#YVRPG2UJ',
            name         : 'Pain..',
            townhallLevel: 13,
            mapPosition  : 18,
            attacks      : [{
                attackerTag          : '#YVRPG2UJ',
                defenderTag          : '#2C2QLRPV',
                stars                : 2,
                destructionPercentage: 98,
                order                : 10,
                duration             : 180,
            }, {
                attackerTag          : '#YVRPG2UJ',
                defenderTag          : '#QJPYLYPCP',
                stars                : 3,
                destructionPercentage: 100,
                order                : 37,
                duration             : 161,
            }],
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#Q8VYCLJVL',
                defenderTag          : '#YVRPG2UJ',
                stars                : 3,
                destructionPercentage: 100,
                order                : 57,
                duration             : 138,
            },
        }, {
            tag          : '#P2QR0PP0Q',
            name         : 'ImFer',
            townhallLevel: 13,
            mapPosition  : 19,
            attacks      : [{
                attackerTag          : '#P2QR0PP0Q',
                defenderTag          : '#2C2QLRPV',
                stars                : 3,
                destructionPercentage: 100,
                order                : 71,
                duration             : 111,
            }],
            opponentAttacks   : 4,
            bestOpponentAttack: {
                attackerTag          : '#QJPYLYPCP',
                defenderTag          : '#P2QR0PP0Q',
                stars                : 3,
                destructionPercentage: 100,
                order                : 84,
                duration             : 109,
            },
        }, {
            tag          : '#9GUPRYQ2Q',
            name         : 'wil',
            townhallLevel: 16,
            mapPosition  : 7,
            attacks      : [{
                attackerTag          : '#9GUPRYQ2Q',
                defenderTag          : '#2RRJG8J2U',
                stars                : 3,
                destructionPercentage: 100,
                order                : 46,
                duration             : 117,
            }, {
                attackerTag          : '#9GUPRYQ2Q',
                defenderTag          : '#G9JP8PCY9',
                stars                : 2,
                destructionPercentage: 75,
                order                : 49,
                duration             : 78,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#2RRJG8J2U',
                defenderTag          : '#9GUPRYQ2Q',
                stars                : 3,
                destructionPercentage: 100,
                order                : 7,
                duration             : 127,
            },
        }, {
            tag               : '#YJ28RP88J',
            name              : 'giovanni',
            townhallLevel     : 15,
            mapPosition       : 9,
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#QJYRYGJG0',
                defenderTag          : '#YJ28RP88J',
                stars                : 3,
                destructionPercentage: 100,
                order                : 27,
                duration             : 157,
            },
        }, {
            tag          : '#PJ999VV8',
            name         : 'Edward',
            townhallLevel: 14,
            mapPosition  : 13,
            attacks      : [{
                attackerTag          : '#PJ999VV8',
                defenderTag          : '#9JV8PUVR0',
                stars                : 3,
                destructionPercentage: 100,
                order                : 55,
                duration             : 145,
            }, {
                attackerTag          : '#PJ999VV8',
                defenderTag          : '#88LJUYVVG',
                stars                : 1,
                destructionPercentage: 79,
                order                : 65,
                duration             : 160,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#9JJYQJVUR',
                defenderTag          : '#PJ999VV8',
                stars                : 3,
                destructionPercentage: 100,
                order                : 2,
                duration             : 106,
            },
        }, {
            tag          : '#20RC08QGR',
            name         : 'Esteban',
            townhallLevel: 14,
            mapPosition  : 11,
            attacks      : [{
                attackerTag          : '#20RC08QGR',
                defenderTag          : '#9JV8PUVR0',
                stars                : 2,
                destructionPercentage: 84,
                order                : 51,
                duration             : 180,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#9JJYQJVUR',
                defenderTag          : '#20RC08QGR',
                stars                : 3,
                destructionPercentage: 100,
                order                : 13,
                duration             : 101,
            },
        }, {
            tag          : '#89RV89UJU',
            name         : 'celia deluzz',
            townhallLevel: 16,
            mapPosition  : 1,
            attacks      : [{
                attackerTag          : '#89RV89UJU',
                defenderTag          : '#92PV2P99G',
                stars                : 3,
                destructionPercentage: 100,
                order                : 42,
                duration             : 123,
            }, {
                attackerTag          : '#89RV89UJU',
                defenderTag          : '#9JJYQJVUR',
                stars                : 3,
                destructionPercentage: 100,
                order                : 43,
                duration             : 103,
            }],
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#LQR0YQVJ',
                defenderTag          : '#89RV89UJU',
                stars                : 3,
                destructionPercentage: 100,
                order                : 6,
                duration             : 148,
            },
        }, {
            tag          : '#L92JVCQC8',
            name         : 'José',
            townhallLevel: 13,
            mapPosition  : 22,
            attacks      : [{
                attackerTag          : '#L92JVCQC8',
                defenderTag          : '#LJ2JGR0P0',
                stars                : 3,
                destructionPercentage: 100,
                order                : 5,
                duration             : 86,
            }, {
                attackerTag          : '#L92JVCQC8',
                defenderTag          : '#9YYR888YQ',
                stars                : 3,
                destructionPercentage: 100,
                order                : 36,
                duration             : 143,
            }],
            opponentAttacks   : 3,
            bestOpponentAttack: {
                attackerTag          : '#LCG99202Q',
                defenderTag          : '#L92JVCQC8',
                stars                : 3,
                destructionPercentage: 100,
                order                : 64,
                duration             : 107,
            },
        }, {
            tag               : '#RUCRCVCU',
            name              : 'yesenia',
            townhallLevel     : 14,
            mapPosition       : 17,
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#QJPYLYPCP',
                defenderTag          : '#RUCRCVCU',
                stars                : 3,
                destructionPercentage: 100,
                order                : 83,
                duration             : 116,
            },
        }, {
            tag          : '#QY88JYJJQ',
            name         : '-(CHELITO)-',
            townhallLevel: 13,
            mapPosition  : 21,
            attacks      : [{
                attackerTag          : '#QY88JYJJQ',
                defenderTag          : '#LCG99202Q',
                stars                : 2,
                destructionPercentage: 96,
                order                : 11,
                duration             : 171,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#8GCC0RPL8',
                defenderTag          : '#QY88JYJJQ',
                stars                : 3,
                destructionPercentage: 100,
                order                : 16,
                duration             : 119,
            },
        }, {
            tag          : '#G0RG2YJU9',
            name         : 'Vlad',
            townhallLevel: 12,
            mapPosition  : 24,
            attacks      : [{
                attackerTag          : '#G0RG2YJU9',
                defenderTag          : '#LCG99202Q',
                stars                : 3,
                destructionPercentage: 100,
                order                : 56,
                duration             : 105,
            }, {
                attackerTag          : '#G0RG2YJU9',
                defenderTag          : '#2C2QLRPV',
                stars                : 2,
                destructionPercentage: 82,
                order                : 70,
                duration             : 141,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#LJ2JGR0P0',
                defenderTag          : '#G0RG2YJU9',
                stars                : 3,
                destructionPercentage: 100,
                order                : 30,
                duration             : 140,
            },
        }, {
            tag          : '#PGG0PCQVP',
            name         : 'BlackCat1207',
            townhallLevel: 14,
            mapPosition  : 15,
            attacks      : [{
                attackerTag          : '#PGG0PCQVP',
                defenderTag          : '#8YJGVYR28',
                stars                : 3,
                destructionPercentage: 100,
                order                : 12,
                duration             : 137,
            }, {
                attackerTag          : '#PGG0PCQVP',
                defenderTag          : '#9JJYQJVUR',
                stars                : 1,
                destructionPercentage: 99,
                order                : 17,
                duration             : 180,
            }],
            opponentAttacks   : 3,
            bestOpponentAttack: {
                attackerTag          : '#G9JP8PCY9',
                defenderTag          : '#PGG0PCQVP',
                stars                : 3,
                destructionPercentage: 100,
                order                : 81,
                duration             : 102,
            },
        }, {
            tag          : '#Q2L8CVPQL',
            name         : 'Sergio',
            townhallLevel: 13,
            mapPosition  : 23,
            attacks      : [{
                attackerTag          : '#Q2L8CVPQL',
                defenderTag          : '#QJCYUVLYL',
                stars                : 3,
                destructionPercentage: 100,
                order                : 47,
                duration             : 125,
            }],
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#LJ2JGR0P0',
                defenderTag          : '#Q2L8CVPQL',
                stars                : 3,
                destructionPercentage: 100,
                order                : 31,
                duration             : 134,
            },
        }, {
            tag          : '#LVG2P8P8Q',
            name         : 'iziiattec',
            townhallLevel: 12,
            mapPosition  : 25,
            attacks      : [{
                attackerTag          : '#LVG2P8P8Q',
                defenderTag          : '#QJCYUVLYL',
                stars                : 2,
                destructionPercentage: 83,
                order                : 34,
                duration             : 127,
            }, {
                attackerTag          : '#LVG2P8P8Q',
                defenderTag          : '#Y2JQPVPY',
                stars                : 3,
                destructionPercentage: 100,
                order                : 35,
                duration             : 74,
            }],
            opponentAttacks   : 3,
            bestOpponentAttack: {
                attackerTag          : '#LCG99202Q',
                defenderTag          : '#LVG2P8P8Q',
                stars                : 3,
                destructionPercentage: 100,
                order                : 61,
                duration             : 144,
            },
        }, {
            tag          : '#R28UJJ9P',
            name         : 'Mervan',
            townhallLevel: 14,
            mapPosition  : 14,
            attacks      : [{
                attackerTag          : '#R28UJJ9P',
                defenderTag          : '#88LJUYVVG',
                stars                : 1,
                destructionPercentage: 77,
                order                : 63,
                duration             : 146,
            }, {
                attackerTag          : '#R28UJJ9P',
                defenderTag          : '#QRGCQ9PRL',
                stars                : 3,
                destructionPercentage: 100,
                order                : 74,
                duration             : 120,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#92PV2P99G',
                defenderTag          : '#R28UJJ9P',
                stars                : 3,
                destructionPercentage: 100,
                order                : 19,
                duration             : 93,
            },
        }, {
            tag          : '#2CCG90UU8',
            name         : 'Alucard',
            townhallLevel: 15,
            mapPosition  : 5,
            attacks      : [{
                attackerTag          : '#2CCG90UU8',
                defenderTag          : '#2VJQRV2YR',
                stars                : 2,
                destructionPercentage: 95,
                order                : 59,
                duration             : 114,
            }, {
                attackerTag          : '#2CCG90UU8',
                defenderTag          : '#2002GULCL',
                stars                : 1,
                destructionPercentage: 56,
                order                : 62,
                duration             : 180,
            }],
            opponentAttacks   : 3,
            bestOpponentAttack: {
                attackerTag          : '#20RYGQQU0',
                defenderTag          : '#2CCG90UU8',
                stars                : 3,
                destructionPercentage: 100,
                order                : 73,
                duration             : 117,
            },
        }, {
            tag          : '#2PVQ2LVJC',
            name         : 'Demon Hunter',
            townhallLevel: 15,
            mapPosition  : 8,
            attacks      : [{
                attackerTag          : '#2PVQ2LVJC',
                defenderTag          : '#2L8QL2PYP',
                stars                : 3,
                destructionPercentage: 100,
                order                : 50,
                duration             : 154,
            }, {
                attackerTag          : '#2PVQ2LVJC',
                defenderTag          : '#QJYRYGJG0',
                stars                : 2,
                destructionPercentage: 91,
                order                : 52,
                duration             : 180,
            }],
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#PQJYQ8VC',
                defenderTag          : '#2PVQ2LVJC',
                stars                : 3,
                destructionPercentage: 100,
                order                : 58,
                duration             : 72,
            },
        }, {
            tag          : '#LJ0Y8YP8J',
            name         : 'lord armando',
            townhallLevel: 16,
            mapPosition  : 2,
            attacks      : [{
                attackerTag          : '#LJ0Y8YP8J',
                defenderTag          : '#LQR0YQVJ',
                stars                : 2,
                destructionPercentage: 61,
                order                : 14,
                duration             : 180,
            }, {
                attackerTag          : '#LJ0Y8YP8J',
                defenderTag          : '#2002GULCL',
                stars                : 2,
                destructionPercentage: 91,
                order                : 68,
                duration             : 180,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#LQR0YQVJ',
                defenderTag          : '#LJ0Y8YP8J',
                stars                : 3,
                destructionPercentage: 100,
                order                : 9,
                duration             : 133,
            },
        }, {
            tag               : '#99YYVR9C8',
            name              : 'Alejandro magno',
            townhallLevel     : 16,
            mapPosition       : 6,
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#20RYGQQU0',
                defenderTag          : '#99YYVR9C8',
                stars                : 3,
                destructionPercentage: 100,
                order                : 72,
                duration             : 105,
            },
        }, {
            tag          : '#Q0R8UCCPG',
            name         : 'Edi',
            townhallLevel: 15,
            mapPosition  : 4,
            attacks      : [{
                attackerTag          : '#Q0R8UCCPG',
                defenderTag          : '#PLCY0P8JG',
                stars                : 2,
                destructionPercentage: 98,
                order                : 41,
                duration             : 180,
            }, {
                attackerTag          : '#Q0R8UCCPG',
                defenderTag          : '#PQJYQ8VC',
                stars                : 3,
                destructionPercentage: 100,
                order                : 44,
                duration             : 134,
            }],
            opponentAttacks   : 4,
            bestOpponentAttack: {
                attackerTag          : '#G9JP8PCY9',
                defenderTag          : '#Q0R8UCCPG',
                stars                : 3,
                destructionPercentage: 100,
                order                : 80,
                duration             : 96,
            },
        }, {
            tag          : '#QP80JYC9U',
            name         : 'Choker',
            townhallLevel: 14,
            mapPosition  : 12,
            attacks      : [{
                attackerTag          : '#QP80JYC9U',
                defenderTag          : '#92PV2P99G',
                stars                : 1,
                destructionPercentage: 98,
                order                : 1,
                duration             : 151,
            }, {
                attackerTag          : '#QP80JYC9U',
                defenderTag          : '#QJYRYGJG0',
                stars                : 2,
                destructionPercentage: 93,
                order                : 78,
                duration             : 176,
            }],
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#92PV2P99G',
                defenderTag          : '#QP80JYC9U',
                stars                : 3,
                destructionPercentage: 100,
                order                : 29,
                duration             : 116,
            },
        }, {
            tag               : '#YPVYPP0C9',
            name              : 'Jendyy',
            townhallLevel     : 14,
            mapPosition       : 16,
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#2VJQRV2YR',
                defenderTag          : '#YPVYPP0C9',
                stars                : 3,
                destructionPercentage: 100,
                order                : 40,
                duration             : 117,
            },
        }],
    },
    opponent: {
        tag      : '#2GR2G0PGG',
        name     : 'DFFP',
        badgeUrls: {
            small : 'https://api-assets.clashofclans.com/badges/70/doJ8o2lsMo8S1bjvj0Y_iDPKZvJNF1uudiaiZZYj5wM.png',
            large : 'https://api-assets.clashofclans.com/badges/512/doJ8o2lsMo8S1bjvj0Y_iDPKZvJNF1uudiaiZZYj5wM.png',
            medium: 'https://api-assets.clashofclans.com/badges/200/doJ8o2lsMo8S1bjvj0Y_iDPKZvJNF1uudiaiZZYj5wM.png',
        },
        clanLevel            : 14,
        attacks              : 46,
        stars                : 75,
        destructionPercentage: 100.0,
        members              : [{
            tag          : '#Y2JQPVPY',
            name         : 'Brainfull',
            townhallLevel: 11,
            mapPosition  : 25,
            attacks      : [{
                attackerTag          : '#Y2JQPVPY',
                defenderTag          : '#LVG2P8P8Q',
                stars                : 2,
                destructionPercentage: 90,
                order                : 24,
                duration             : 162,
            }, {
                attackerTag          : '#Y2JQPVPY',
                defenderTag          : '#L92JVCQC8',
                stars                : 1,
                destructionPercentage: 68,
                order                : 48,
                duration             : 100,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#LVG2P8P8Q',
                defenderTag          : '#Y2JQPVPY',
                stars                : 3,
                destructionPercentage: 100,
                order                : 35,
                duration             : 74,
            },
        }, {
            tag          : '#Q8VYCLJVL',
            name         : 'gkb',
            townhallLevel: 13,
            mapPosition  : 17,
            attacks      : [{
                attackerTag          : '#Q8VYCLJVL',
                defenderTag          : '#RUCRCVCU',
                stars                : 2,
                destructionPercentage: 83,
                order                : 3,
                duration             : 126,
            }, {
                attackerTag          : '#Q8VYCLJVL',
                defenderTag          : '#YVRPG2UJ',
                stars                : 3,
                destructionPercentage: 100,
                order                : 57,
                duration             : 138,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#8ULU8LUG0',
                defenderTag          : '#Q8VYCLJVL',
                stars                : 3,
                destructionPercentage: 100,
                order                : 54,
                duration             : 174,
            },
        }, {
            tag          : '#9YYR888YQ',
            name         : 'neuro',
            townhallLevel: 14,
            mapPosition  : 21,
            attacks      : [{
                attackerTag          : '#9YYR888YQ',
                defenderTag          : '#LVG2P8P8Q',
                stars                : 2,
                destructionPercentage: 73,
                order                : 4,
                duration             : 180,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#L92JVCQC8',
                defenderTag          : '#9YYR888YQ',
                stars                : 3,
                destructionPercentage: 100,
                order                : 36,
                duration             : 143,
            },
        }, {
            tag          : '#QJPYLYPCP',
            name         : 'faygat',
            townhallLevel: 14,
            mapPosition  : 19,
            attacks      : [{
                attackerTag          : '#QJPYLYPCP',
                defenderTag          : '#RUCRCVCU',
                stars                : 3,
                destructionPercentage: 100,
                order                : 83,
                duration             : 116,
            }, {
                attackerTag          : '#QJPYLYPCP',
                defenderTag          : '#P2QR0PP0Q',
                stars                : 3,
                destructionPercentage: 100,
                order                : 84,
                duration             : 109,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#YVRPG2UJ',
                defenderTag          : '#QJPYLYPCP',
                stars                : 3,
                destructionPercentage: 100,
                order                : 37,
                duration             : 161,
            },
        }, {
            tag               : '#2C2QLRPV',
            name              : 'Tyler',
            townhallLevel     : 13,
            mapPosition       : 18,
            opponentAttacks   : 3,
            bestOpponentAttack: {
                attackerTag          : '#P2QR0PP0Q',
                defenderTag          : '#2C2QLRPV',
                stars                : 3,
                destructionPercentage: 100,
                order                : 71,
                duration             : 111,
            },
        }, {
            tag          : '#2L8QL2PYP',
            name         : 'PHAT PANDA',
            townhallLevel: 15,
            mapPosition  : 11,
            attacks      : [{
                attackerTag          : '#2L8QL2PYP',
                defenderTag          : '#2PVQ2LVJC',
                stars                : 1,
                destructionPercentage: 72,
                order                : 45,
                duration             : 105,
            }, {
                attackerTag          : '#2L8QL2PYP',
                defenderTag          : '#P2QR0PP0Q',
                stars                : 1,
                destructionPercentage: 78,
                order                : 82,
                duration             : 107,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#2PVQ2LVJC',
                defenderTag          : '#2L8QL2PYP',
                stars                : 3,
                destructionPercentage: 100,
                order                : 50,
                duration             : 154,
            },
        }, {
            tag          : '#2VJQRV2YR',
            name         : 'All Mighty Odin',
            townhallLevel: 14,
            mapPosition  : 8,
            attacks      : [{
                attackerTag          : '#2VJQRV2YR',
                defenderTag          : '#PGG0PCQVP',
                stars                : 2,
                destructionPercentage: 72,
                order                : 39,
                duration             : 180,
            }, {
                attackerTag          : '#2VJQRV2YR',
                defenderTag          : '#YPVYPP0C9',
                stars                : 3,
                destructionPercentage: 100,
                order                : 40,
                duration             : 117,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#2CCG90UU8',
                defenderTag          : '#2VJQRV2YR',
                stars                : 2,
                destructionPercentage: 95,
                order                : 59,
                duration             : 114,
            },
        }, {
            tag          : '#PLCY0P8JG',
            name         : 'Oathkeeper',
            townhallLevel: 16,
            mapPosition  : 4,
            attacks      : [{
                attackerTag          : '#PLCY0P8JG',
                defenderTag          : '#Q0R8UCCPG',
                stars                : 2,
                destructionPercentage: 99,
                order                : 76,
                duration             : 180,
            }, {
                attackerTag          : '#PLCY0P8JG',
                defenderTag          : '#89RV89UJU',
                stars                : 2,
                destructionPercentage: 94,
                order                : 77,
                duration             : 151,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#Q0R8UCCPG',
                defenderTag          : '#PLCY0P8JG',
                stars                : 2,
                destructionPercentage: 98,
                order                : 41,
                duration             : 180,
            },
        }, {
            tag          : '#QJCYUVLYL',
            name         : 'charlie',
            townhallLevel: 12,
            mapPosition  : 24,
            attacks      : [{
                attackerTag          : '#QJCYUVLYL',
                defenderTag          : '#YVRPG2UJ',
                stars                : 2,
                destructionPercentage: 74,
                order                : 32,
                duration             : 149,
            }, {
                attackerTag          : '#QJCYUVLYL',
                defenderTag          : '#P2QR0PP0Q',
                stars                : 2,
                destructionPercentage: 81,
                order                : 33,
                duration             : 130,
            }],
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#Q2L8CVPQL',
                defenderTag          : '#QJCYUVLYL',
                stars                : 3,
                destructionPercentage: 100,
                order                : 47,
                duration             : 125,
            },
        }, {
            tag          : '#LCG99202Q',
            name         : 'Braden30',
            townhallLevel: 12,
            mapPosition  : 22,
            attacks      : [{
                attackerTag          : '#LCG99202Q',
                defenderTag          : '#LVG2P8P8Q',
                stars                : 3,
                destructionPercentage: 100,
                order                : 61,
                duration             : 144,
            }, {
                attackerTag          : '#LCG99202Q',
                defenderTag          : '#L92JVCQC8',
                stars                : 3,
                destructionPercentage: 100,
                order                : 64,
                duration             : 107,
            }],
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#G0RG2YJU9',
                defenderTag          : '#LCG99202Q',
                stars                : 3,
                destructionPercentage: 100,
                order                : 56,
                duration             : 105,
            },
        }, {
            tag          : '#PQJYQ8VC',
            name         : 'Kitchens',
            townhallLevel: 15,
            mapPosition  : 7,
            attacks      : [{
                attackerTag          : '#PQJYQ8VC',
                defenderTag          : '#2PVQ2LVJC',
                stars                : 3,
                destructionPercentage: 100,
                order                : 58,
                duration             : 72,
            }, {
                attackerTag          : '#PQJYQ8VC',
                defenderTag          : '#2CCG90UU8',
                stars                : 2,
                destructionPercentage: 97,
                order                : 60,
                duration             : 180,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#Q0R8UCCPG',
                defenderTag          : '#PQJYQ8VC',
                stars                : 3,
                destructionPercentage: 100,
                order                : 44,
                duration             : 134,
            },
        }, {
            tag          : '#9JJYQJVUR',
            name         : 'himanshu',
            townhallLevel: 14,
            mapPosition  : 13,
            attacks      : [{
                attackerTag          : '#9JJYQJVUR',
                defenderTag          : '#PJ999VV8',
                stars                : 3,
                destructionPercentage: 100,
                order                : 2,
                duration             : 106,
            }, {
                attackerTag          : '#9JJYQJVUR',
                defenderTag          : '#20RC08QGR',
                stars                : 3,
                destructionPercentage: 100,
                order                : 13,
                duration             : 101,
            }],
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#89RV89UJU',
                defenderTag          : '#9JJYQJVUR',
                stars                : 3,
                destructionPercentage: 100,
                order                : 43,
                duration             : 103,
            },
        }, {
            tag          : '#20RYGQQU0',
            name         : 'GobHobbler',
            townhallLevel: 15,
            mapPosition  : 6,
            attacks      : [{
                attackerTag          : '#20RYGQQU0',
                defenderTag          : '#99YYVR9C8',
                stars                : 3,
                destructionPercentage: 100,
                order                : 72,
                duration             : 105,
            }, {
                attackerTag          : '#20RYGQQU0',
                defenderTag          : '#2CCG90UU8',
                stars                : 3,
                destructionPercentage: 100,
                order                : 73,
                duration             : 117,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#8ULU8LUG0',
                defenderTag          : '#20RYGQQU0',
                stars                : 2,
                destructionPercentage: 65,
                order                : 38,
                duration             : 169,
            },
        }, {
            tag          : '#LJ2JGR0P0',
            name         : 'bob',
            townhallLevel: 12,
            mapPosition  : 23,
            attacks      : [{
                attackerTag          : '#LJ2JGR0P0',
                defenderTag          : '#G0RG2YJU9',
                stars                : 3,
                destructionPercentage: 100,
                order                : 30,
                duration             : 140,
            }, {
                attackerTag          : '#LJ2JGR0P0',
                defenderTag          : '#Q2L8CVPQL',
                stars                : 3,
                destructionPercentage: 100,
                order                : 31,
                duration             : 134,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#L92JVCQC8',
                defenderTag          : '#LJ2JGR0P0',
                stars                : 3,
                destructionPercentage: 100,
                order                : 5,
                duration             : 86,
            },
        }, {
            tag          : '#2RRJG8J2U',
            name         : '"R.P.K"',
            townhallLevel: 16,
            mapPosition  : 5,
            attacks      : [{
                attackerTag          : '#2RRJG8J2U',
                defenderTag          : '#9GUPRYQ2Q',
                stars                : 3,
                destructionPercentage: 100,
                order                : 7,
                duration             : 127,
            }, {
                attackerTag          : '#2RRJG8J2U',
                defenderTag          : '#Q0R8UCCPG',
                stars                : 1,
                destructionPercentage: 60,
                order                : 8,
                duration             : 114,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#9GUPRYQ2Q',
                defenderTag          : '#2RRJG8J2U',
                stars                : 3,
                destructionPercentage: 100,
                order                : 46,
                duration             : 117,
            },
        }, {
            tag          : '#G9JP8PCY9',
            name         : 'NotStr8DontH8',
            townhallLevel: 16,
            mapPosition  : 3,
            attacks      : [{
                attackerTag          : '#G9JP8PCY9',
                defenderTag          : '#Q0R8UCCPG',
                stars                : 3,
                destructionPercentage: 100,
                order                : 80,
                duration             : 96,
            }, {
                attackerTag          : '#G9JP8PCY9',
                defenderTag          : '#PGG0PCQVP',
                stars                : 3,
                destructionPercentage: 100,
                order                : 81,
                duration             : 102,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#9GUPRYQ2Q',
                defenderTag          : '#G9JP8PCY9',
                stars                : 2,
                destructionPercentage: 75,
                order                : 49,
                duration             : 78,
            },
        }, {
            tag          : '#2002GULCL',
            name         : 'Ruck',
            townhallLevel: 16,
            mapPosition  : 1,
            attacks      : [{
                attackerTag          : '#2002GULCL',
                defenderTag          : '#Q20LRR0YY',
                stars                : 3,
                destructionPercentage: 100,
                order                : 75,
                duration             : 107,
            }, {
                attackerTag          : '#2002GULCL',
                defenderTag          : '#Q0R8UCCPG',
                stars                : 2,
                destructionPercentage: 80,
                order                : 79,
                duration             : 134,
            }],
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#LJ0Y8YP8J',
                defenderTag          : '#2002GULCL',
                stars                : 2,
                destructionPercentage: 91,
                order                : 68,
                duration             : 180,
            },
        }, {
            tag          : '#8GCC0RPL8',
            name         : 'Dragon',
            townhallLevel: 13,
            mapPosition  : 20,
            attacks      : [{
                attackerTag          : '#8GCC0RPL8',
                defenderTag          : '#PP0JVP00',
                stars                : 3,
                destructionPercentage: 100,
                order                : 15,
                duration             : 151,
            }, {
                attackerTag          : '#8GCC0RPL8',
                defenderTag          : '#QY88JYJJQ',
                stars                : 3,
                destructionPercentage: 100,
                order                : 16,
                duration             : 119,
            }],
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#Q20LRR0YY',
                defenderTag          : '#8GCC0RPL8',
                stars                : 3,
                destructionPercentage: 100,
                order                : 69,
                duration             : 85,
            },
        }, {
            tag          : '#QJYRYGJG0',
            name         : 'Barry Kv',
            townhallLevel: 14,
            mapPosition  : 10,
            attacks      : [{
                attackerTag          : '#QJYRYGJG0',
                defenderTag          : '#8ULU8LUG0',
                stars                : 3,
                destructionPercentage: 100,
                order                : 26,
                duration             : 140,
            }, {
                attackerTag          : '#QJYRYGJG0',
                defenderTag          : '#YJ28RP88J',
                stars                : 3,
                destructionPercentage: 100,
                order                : 27,
                duration             : 157,
            }],
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#QP80JYC9U',
                defenderTag          : '#QJYRYGJG0',
                stars                : 2,
                destructionPercentage: 93,
                order                : 78,
                duration             : 176,
            },
        }, {
            tag          : '#88LJUYVVG',
            name         : 'hector',
            townhallLevel: 14,
            mapPosition  : 9,
            attacks      : [{
                attackerTag          : '#88LJUYVVG',
                defenderTag          : '#99YYVR9C8',
                stars                : 2,
                destructionPercentage: 61,
                order                : 66,
                duration             : 180,
            }],
            opponentAttacks   : 3,
            bestOpponentAttack: {
                attackerTag          : '#Q20LRR0YY',
                defenderTag          : '#88LJUYVVG',
                stars                : 3,
                destructionPercentage: 100,
                order                : 67,
                duration             : 160,
            },
        }, {
            tag          : '#QRGCQ9PRL',
            name         : 'mr_Rahul__❤️',
            townhallLevel: 13,
            mapPosition  : 16,
            attacks      : [{
                attackerTag          : '#QRGCQ9PRL',
                defenderTag          : '#P2QR0PP0Q',
                stars                : 1,
                destructionPercentage: 88,
                order                : 22,
                duration             : 133,
            }, {
                attackerTag          : '#QRGCQ9PRL',
                defenderTag          : '#2CCG90UU8',
                stars                : 2,
                destructionPercentage: 74,
                order                : 23,
                duration             : 141,
            }],
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#R28UJJ9P',
                defenderTag          : '#QRGCQ9PRL',
                stars                : 3,
                destructionPercentage: 100,
                order                : 74,
                duration             : 120,
            },
        }, {
            tag          : '#92PV2P99G',
            name         : 'Gob, too',
            townhallLevel: 14,
            mapPosition  : 12,
            attacks      : [{
                attackerTag          : '#92PV2P99G',
                defenderTag          : '#R28UJJ9P',
                stars                : 3,
                destructionPercentage: 100,
                order                : 19,
                duration             : 93,
            }, {
                attackerTag          : '#92PV2P99G',
                defenderTag          : '#QP80JYC9U',
                stars                : 3,
                destructionPercentage: 100,
                order                : 29,
                duration             : 116,
            }],
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#89RV89UJU',
                defenderTag          : '#92PV2P99G',
                stars                : 3,
                destructionPercentage: 100,
                order                : 42,
                duration             : 123,
            },
        }, {
            tag          : '#9JV8PUVR0',
            name         : 'Devil',
            townhallLevel: 14,
            mapPosition  : 14,
            attacks      : [{
                attackerTag          : '#9JV8PUVR0',
                defenderTag          : '#L92JVCQC8',
                stars                : 2,
                destructionPercentage: 74,
                order                : 20,
                duration             : 112,
            }, {
                attackerTag          : '#9JV8PUVR0',
                defenderTag          : '#Q2L8CVPQL',
                stars                : 1,
                destructionPercentage: 84,
                order                : 21,
                duration             : 180,
            }],
            opponentAttacks   : 2,
            bestOpponentAttack: {
                attackerTag          : '#PJ999VV8',
                defenderTag          : '#9JV8PUVR0',
                stars                : 3,
                destructionPercentage: 100,
                order                : 55,
                duration             : 145,
            },
        }, {
            tag          : '#LQR0YQVJ',
            name         : 'lost soul',
            townhallLevel: 16,
            mapPosition  : 2,
            attacks      : [{
                attackerTag          : '#LQR0YQVJ',
                defenderTag          : '#89RV89UJU',
                stars                : 3,
                destructionPercentage: 100,
                order                : 6,
                duration             : 148,
            }, {
                attackerTag          : '#LQR0YQVJ',
                defenderTag          : '#LJ0Y8YP8J',
                stars                : 3,
                destructionPercentage: 100,
                order                : 9,
                duration             : 133,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#LJ0Y8YP8J',
                defenderTag          : '#LQR0YQVJ',
                stars                : 2,
                destructionPercentage: 61,
                order                : 14,
                duration             : 180,
            },
        }, {
            tag          : '#8YJGVYR28',
            name         : 'Paardso',
            townhallLevel: 14,
            mapPosition  : 15,
            attacks      : [{
                attackerTag          : '#8YJGVYR28',
                defenderTag          : '#PGG0PCQVP',
                stars                : 1,
                destructionPercentage: 84,
                order                : 25,
                duration             : 160,
            }, {
                attackerTag          : '#8YJGVYR28',
                defenderTag          : '#QP80JYC9U',
                stars                : 1,
                destructionPercentage: 80,
                order                : 28,
                duration             : 121,
            }],
            opponentAttacks   : 1,
            bestOpponentAttack: {
                attackerTag          : '#PGG0PCQVP',
                defenderTag          : '#8YJGVYR28',
                stars                : 3,
                destructionPercentage: 100,
                order                : 12,
                duration             : 137,
            },
        }],
    },
    status_code    : 200,
    timestamp      : 1724638464.26468,
    _response_retry: 120,
}];

describe('ope', () => {
    it('test', () => {
        const [actual] = mapWars('#U8YURJG0', given);

        console.log(actual.mirror_th_diff);
    });
});
