export const DISCORD_APP_ID = 'DISCORD_APP_ID';
export const DISCORD_PUBLIC_KEY = 'DISCORD_PUBLIC_KEY';
export const DISCORD_CLIENT_ID = 'DISCORD_CLIENT_ID';
export const DISCORD_CLIENT_SECRET = 'DISCORD_CLIENT_SECRET';
export const DISCORD_ERROR_URL = 'DISCORD_ERROR_URL';
export const DISCORD_DEBUG_URL = 'DISCORD_DEBUG_URL';

export const COC_USER = 'COC_USER';
export const COC_PASSWORD = 'COC_PASSWORD';
